Vagrant.configure("2") do |config|
  config.vm.define "db" do |server|
    server.vm.box = "ubuntu/xenial64"

  server.vm.network "private_network", ip: "192.168.10.150"
  server.hostsupdater.aliases = ["development.local"]

  server.vm.synced_folder "db_config/.", "/home/vagrant/app"
  server.vm.provision :shell,  path: "./dbprovision.sh"
end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"

  web.vm.network "private_network", ip: "192.168.10.100"
  web.hostsupdater.aliases = ["development.local"]

  web.vm.synced_folder "webserver/.", "/home/vagrant/app"
  web.vm.provision :shell, path: "./provision.sh"


end
end
